# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.Especie'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.Animal'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.Genero'),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.Vacuna'),
        ),
    ]
