# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganaderia', '0003_auto_20181118_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('descripcion', models.TextField(max_length=255)),
                ('peso', models.IntegerField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
